name: Run colossalqa unit tests

on:
  pull_request:
    types: [synchronize, opened, reopened]
    paths:
      - 'applications/langchain/colossalqa/**'
      - 'applications/langchain/requirements.txt'
      - 'applications/langchain/setup.py'
      - 'applications/langchain/tests/**'
      - 'applications/langchain/pytest.ini'

jobs:
  tests:
    name: Run colossalqa unit tests
    if: |
      github.event.pull_request.draft == false &&
      github.base_ref == 'main' &&
      github.event.pull_request.base.repo.full_name == 'hpcaitech/ColossalAI'
    runs-on: [self-hosted, 8-gpu]
    container:
      image: hpcaitech/pytorch-cuda:1.12.0-11.3.0
      options: --gpus all --rm -v /data/scratch/chatgpt:/data/scratch/chatgpt
    timeout-minutes: 30
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout ColossalAI
        uses: actions/checkout@v2

      - name: Install colossalqa
        run: |
          cd applications/langchain
          pip install -e .

      - name: Execute Unit Testing
        run: |
          cd applications/langchain
          pytest tests/
        env:
          NCCL_SHM_DISABLE: 1
          MAX_JOBS: 8
          ZH_MODEL_PATH: /data3/data/model_eval_for_non_commercial_use/chatglm2-6b
          ZH_MODEL_NAME: chatglm2
          EN_MODEL_PATH: /data3/data/model_eval_for_commerical_use/Llama-2-7b-hf
          EN_MODEL_NAME: llama
          TEST_DATA_PATH_EN: /data3/users/lcyab/ColossalAI/applications/langchain/data/test_data/companies.txt
          TEST_DATA_PATH_ZH: /data3/users/lcyab/ColossalAI/applications/langchain/data/test_data/companies_zh.txt